fir_tagartifact/urls.py
from django.conf.urls import url

from fir_tagartifact import views

urlpatterns = [
    url(r'^(?P<content_type>\d+)/add/(?P<object_id>\d+)$', views.tagartifact_addtag, name='add'),
]

fir_tagartifact/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from incidents.models import IncidentCategory


class ValidTag(models.Model):
    name = models.CharField(max_length=30, verbose_name=_("Name"))
    description = models.CharField(max_length=100, verbose_name=_("Description"), null=True, blank=True)
    categories = models.ManyToManyField(IncidentCategory, related_name='valid_tags', verbose_name=_("Categories"))

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _("Valid tag")
        verbose_name_plural = _("Valid tags")

fir_tagartifact/forms.py
from django import forms
from fir_tagartifact.models import ValidTag


class TagForm(forms.Form):
    name = forms.ModelChoiceField(queryset=ValidTag.objects.all(), required=True)
    value = forms.CharField(min_length=3, required=True)

    def __init__(self, category, *args, **kwargs):
        self.base_fields['name'].queryset = category.valid_tags.all()
        super(TagForm, self).__init__(*args, **kwargs)

fir_tagartifact/views.py
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template.loader import render_to_string
from django.http import JsonResponse

from fir_artifacts.models import Artifact
from fir_tagartifact.forms import TagForm

from fir_tagartifact.tag import Tag


@login_required
def tagartifact_addtag(request, content_type=None, object_id=None):
    object_type = ContentType.objects.get(pk=content_type)
    obj = get_object_or_404(object_type.model_class(), pk=object_id)
    if not request.user.has_perm('incidents.handle_incidents', obj=obj):
        raise PermissionDenied()
    if request.method == "GET":
        tag_form = TagForm(obj.category)

    if request.method == 'POST':
        tag_form = TagForm(obj.category, request.POST)

        if tag_form.is_valid():
            value = "{name}: {value}".format(name=tag_form.cleaned_data['name'].name,
                                             value=tag_form.cleaned_data['value'])
            try:
                artifact = Artifact.objects.get(type=Tag.key, value__iexact=value)
            except Artifact.DoesNotExist:
                artifact = Artifact.objects.create(type=Tag.key, value=value)
            except Artifact.MultipleObjectsReturned:
                try:
                    artifact = Artifact.objects.get(type=Tag.key, value=value)
                except Artifact.DoesNotExist:
                    artifact = Artifact.objects.create(type=Tag.key, value=value)
                except Artifact.MultipleObjectsReturned:
                    artifact = Artifact.objects.get(type=Tag.key, value=value)[0]
            artifact.relations.add(obj)
            artifact.save()
            ret = {'status': 'success'}
            return JsonResponse(ret)
        else:
            errors = render_to_string("fir_tagartifact/tag_form.html",
                                      {'tag_form': tag_form, 'obj_id': object_id, 'obj_type': content_type})
            ret = {'status': 'error', 'data': errors}
            return JsonResponse(ret)

    return render(request, "fir_tagartifact/tag_form.html",
                  {'tag_form': tag_form, 'obj_id': object_id, 'obj_type': content_type})

fir_tagartifact/templates/fir_tagartifact/plugins/details_actions_add.html
{% load i18n %}
{% load fir_plugins %}
{% load authorization %}

{% if event.category and event.category.valid_tags.count %}
{%  has_perm 'incidents.handle_incidents' obj=event as can_handle_incident %}
{% if can_handle_incident %}
<li>
	<a href="#" id='add-tag' data-url="{% url 'tagartifact:add' event|content_type event.id %}">
		<i class="glyphicon glyphicon-tag"></i>{% trans "Tag" %}
	</a>
</li>
{% endif %}
{% endif %}

fir_tagartifact/templates/fir_tagartifact/plugins/details_static.html
{% load staticfiles %}
<script src="{% static "fir_tagartifact/tags.js" %}"></script>
<div id='tag_modals'>
</div>

fir_tagartifact/templates/fir_tagartifact/tag_form.html
{% load add_css_class %}
{% load i18n %}
{% load fir_artifacts %}

<div id="addTag" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="addTagLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
		  	<div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 id="addTagLabel" class="modal-title">{% trans "Add tag" %}</h4>
		  	</div>
            <form id="tag_form" action="{% url 'tagartifact:add' obj_type obj_id %}" method="POST">
			  	<div class="modal-body">
					{% csrf_token %}

					<div id="name_control_group" class='form-group {% if tag_form.date.errors%} error{%endif%}'>
									<label for="id_name" class="control-label name-label">{% trans "Tag name" %}</label>
									<div class='controls'>
										{{ tag_form.name|add_css_class:'form-control' }}
										<span class='help-block'>{% for error in tag_form.name.errors %}{{ error }}{% endfor %}</span>
									</div>
							</div>

							<div id="value_timestamp_control_group" class='form-group {% if tag_form.value.errors%} error{%endif%}'>
									<label for="id_value" class="control-label value-label">{% trans "Tag value" %}</label>
									<div class='controls'>
										{{ tag_form.value|add_css_class:'form-control' }}
										<span class='help-block'>{% for error in tag_form.value.errors %}{{ error }}{% endfor %}</span>
									</div>
							</div>
			  	</div>
				<div class="modal-footer">
					<button class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button">{% trans "Cancel" %}</button>
					<button class="btn btn-primary" id='submit-tag' type="submit">{% trans "Add tag" %}</button>
			  </div>
		  </form>
		</div>
	</div>
</div>